"""
Shared configuration for the causal-safe preprocessing pipelines.

One pipeline, three datasets (Hillstrom, X5 RetailHero, Lenta).  Everything that
is *not* dataset-specific lives here; dataset-specific column maps and cleaning
logic live in ``causal_prep.datasets.<name>``.
"""

from __future__ import annotations

from pathlib import Path

# --------------------------------------------------------------------------- #
# Paths  (data/raw is immutable; everything else is regenerated by the pipeline)
# --------------------------------------------------------------------------- #
REPO_ROOT = Path(__file__).resolve().parents[2]

DATA_RAW = REPO_ROOT / "data" / "raw"
DATA_INTERIM = REPO_ROOT / "data" / "interim"
DATA_PROCESSED = REPO_ROOT / "data" / "processed"
ARTIFACTS = REPO_ROOT / "artifacts"
REPORTS = REPO_ROOT / "reports"

# Canonical raw locations (data/raw/<ds>/ holds symlinks into datasets/ for the
# two datasets shipped with the repo, and the real download for Lenta).
RAW_FILES = {
    "hillstrom": DATA_RAW / "hillstrom" / "hillstrom.csv",
    "x5_dir": DATA_RAW / "x5" / "x5-retail-hero-uplift-raw-data",
    "lenta": DATA_RAW / "lenta" / "lenta_dataset.csv.gz",
}

# --------------------------------------------------------------------------- #
# Reproducibility  (identical policy across datasets)
# --------------------------------------------------------------------------- #
RANDOM_SEED = 20240501
TEST_SIZE = 0.20

# --------------------------------------------------------------------------- #
# Diagnostic thresholds
# --------------------------------------------------------------------------- #
SMD_FLAG = 0.10                  # |standardized mean diff| above this = imbalance
PROPENSITY_TRIM = (0.01, 0.99)  # positivity: report mass outside this band
PROPENSITY_AUC_RCT_BAND = (0.45, 0.55)  # expected for a real RCT


def ensure_dirs(name: str) -> dict[str, Path]:
    """Create and return the output directories for one dataset."""
    d = {
        "interim": DATA_INTERIM / name,
        "processed": DATA_PROCESSED / name,
        "artifacts": ARTIFACTS / name,
        "reports": REPORTS / name,
        "figures": REPORTS / name / "figures",
    }
    for p in d.values():
        p.mkdir(parents=True, exist_ok=True)
    return d
